spring:
  application:
    name: configserver
  #profiles:
    #active: native
  cloud:
    config:
      server:
        git: 
         uri: https://github.com/Poonam00/config-repo
         searchPaths: '{application}'
        #native:
         #   search-locations: file:///E:/myworkspace
        #bootstrap: true
server:
  port: 8888
